# To do:
* compare variable month and years to stata read data to verify reading them correctly
* make github page for this

In [1]:
################### import packages #######################################################
import pandas as pd
import re
import numpy as np
import os
from hrs_functions import *
import copy 
%load_ext line_profiler
pd.set_option('display.max_columns', None)
## maybe make this more programatic
## each survey has a letter preceeding variable names, increases by 1 each time
var_dict = {
     2002: 'h'
    , 2004: 'j' # they skip i for some reason
    , 2006: 'k'
    , 2008: 'l'
    , 2010: 'm'
    , 2012: 'n'
    , 2014: 'o'
    , 2016: 'p' 
}

In [ ]:
test = pd.read_stata('/Users/jcoven/Desktop/H16A_R.dta')
test

In [2]:
dct_file = '/Users/jcoven/Desktop/HRS_Assembly/python/data/h02sas/H02A_R.sas'
filename = '/Users/jcoven/Desktop/HRS_Assembly/python/data/h02da/H02A_R.da'

# to improve speed of code
#%lprun -f read_sas_fwf read_sas_fwf(dct_file, filename)
cwd = os.getcwd()
variables_to_look_for = {'a500':'rmonth_survey'
                         , 'a501':'ryear_survey'
                         , 'j073m1':'rjobwhym1'
                         , 'lb032_2':'rrisk_financial'
                         , 'n106':'rhosp_cost_oop'}

survey_year = 2002





read_sas_fwf(dct_file, filename, variables_to_look_for, survey_year)

         HHID   PN  HA500   HA501
0      000003  010    4.0  2002.0
1      000003  020    4.0  2002.0
2      010001  010    4.0  2002.0
3      010003  030    8.0  2002.0
4      010004  010    4.0  2002.0
5      010004  040    1.0  2003.0
6      010013  010    4.0  2002.0
7      010013  040    4.0  2002.0
8      010038  010    5.0  2002.0
9      010038  040    6.0  2002.0
10     010050  010    5.0  2002.0
11     010059  020    5.0  2002.0
12     010059  030    6.0  2002.0
13     010075  020    7.0  2002.0
14     010075  030    7.0  2002.0
15     010083  010    4.0  2002.0
16     010083  020    4.0  2002.0
17     010097  040    4.0  2002.0
18     010099  010    1.0  2003.0
19     010106  010    8.0  2002.0
20     010109  030    1.0  2003.0
21     010124  010    4.0  2002.0
22     010147  010    5.0  2002.0
23     010196  010    4.0  2002.0
24     010206  010    4.0  2002.0
25     010210  010    5.0  2002.0
26     010210  020    5.0  2002.0
27     010225  010    4.0  2002.0
28     010240  010   10.0  2002.0
29     010281  010    5.0  2002.0
...       ...  ...    ...     ...
18137  213429  010    7.0  2002.0
18138  213429  020    7.0  2002.0
18139  213430  010    5.0  2002.0
18140  213434  010   12.0  2002.0
18141  213435  010    5.0  2002.0
18142  213439  010    7.0  2002.0
18143  213441  010    5.0  2002.0
18144  213441  020    5.0  2002.0
18145  213442  010    6.0  2002.0
18146  213442  020    6.0  2002.0
18147  213443  010    7.0  2002.0
18148  213444  010    7.0  2002.0
18149  213444  020    6.0  2002.0
18150  213446  010   11.0  2002.0
18151  213446  020   10.0  2002.0
18152  213448  010    2.0  2003.0
18153  213449  010    6.0  2002.0
18154  213449  020    6.0  2002.0
18155  213450  010    5.0  2002.0
18156  213455  010   10.0  2002.0
18157  213465  010    9.0  2002.0
18158  213466  010   10.0  2002.0
18159  213466  011   10.0  2002.0
18160  213467  010    5.0  2002.0
18161  213467  020    5.0  2002.0
18162  213468  010    9.0  2002.0
18163  213471  010    6.0  2002.0
18164  213475  010    7.0  2002.0
18165  213479  010    6.0  2002.0
18166  213479  020    6.0  2002.0

[18167 rows x 4 columns]

In [4]:
cwd = os.getcwd()
variables_to_look_for = {'a500':'rmonth_survey'
                         , 'a501':'ryear_survey'
                         , 'j073m1':'rjobwhym1'
                         , 'lb032_2':'rrisk_financial'
                         , 'n106':'rhosp_cost_oop'}
survey_year = 2016
directory = cwd + '/data/'

    
#sas_read_year(directory, variables_to_look_for, survey_year)

#%lprun -f sas_read_year sas_read_year(directory, variables_to_look_for, survey_year)

In [10]:
years = [2002, 2004, 2006, 2008, 2012, 2014, 2016]
def read_hrs_all_years(years, directory, variables_to_look_for):
    for i in range(len(years)):
        yr = years[i]
        print('reading files for survey year: ' + str(yr))
        if i == 0:
            year_frame = sas_read_year(directory, variables_to_look_for, yr)
        else:
            temp_df = sas_read_year(directory, variables_to_look_for, yr)
            year_frame = year_frame.append(temp_df)
        print('\n')
    return year_frame
    
output = read_hrs_all_years(years, directory, variables_to_look_for)
output

reading files for survey year: 2002
/Users/jcoven/Desktop/HRS_Assembly/python/data/h02da/H02N_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h02sas/H02N_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h02da/H02A_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h02sas/H02A_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h02da/H02L_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h02sas/H02L_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h02da/H02J_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h02sas/H02J_R.sas


reading files for survey year: 2004
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04da/H04A_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04sas/H04A_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04da/H04LB_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04sas/H04LB_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04da/H04J_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04sas/H04J_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04da/H04L_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04sas/H04L_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04da/H04N_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h04sas/H04N_R.sas


reading files for survey year: 2006
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06da/H06L_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06sas/H06L_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06da/H06LB_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06sas/H06LB_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06da/H06N_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06sas/H06N_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06da/H06A_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06sas/H06A_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06da/H06J_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h06sas/H06J_R.sas


reading files for survey year: 2008
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08da/H08L_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08sas/H08L_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08da/H08N_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08sas/H08N_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08da/H08A_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08sas/H08A_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08da/H08J_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08sas/H08J_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08da/H08LB_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h08sas/H08LB_R.sas


reading files for survey year: 2012
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12da/H12L_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12sas/H12L_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12da/H12A_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12sas/H12A_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12da/H12J_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12sas/H12J_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12da/H12LB_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12sas/H12LB_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12da/H12N_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h12sas/H12N_R.sas


reading files for survey year: 2014
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14da/H14N_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14sas/H14N_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14da/H14J_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14sas/H14J_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14da/H14L_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14sas/H14L_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14da/H14LB_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14sas/H14LB_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14da/H14A_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h14sas/H14A_R.sas


reading files for survey year: 2016
/Users/jcoven/Desktop/HRS_Assembly/python/data/h16da/H16A_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h16sas/H16A_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h16da/H16LB_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h16sas/H16LB_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h16da/H16J_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h16sas/H16J_R.sas
/Users/jcoven/Desktop/HRS_Assembly/python/data/h16da/H16N_R.da
/Users/jcoven/Desktop/HRS_Assembly/python/data/h16sas/H16N_R.sas

,HHID,PN,rhosp_cost_oop,rjobwhym1,rmonth_survey,rrisk_financial,ryear_survey,wave
0,000003,010,NaN,NaN,4.0,NaN,2002.0,6.0
1,000003,020,NaN,NaN,4.0,NaN,2002.0,6.0
2,010001,010,NaN,NaN,4.0,NaN,2002.0,6.0
3,010003,030,NaN,NaN,8.0,NaN,2002.0,6.0
4,010004,010,500,NaN,4.0,NaN,2002.0,6.0
5,010004,040,NaN,NaN,1.0,NaN,2003.0,6.0
6,010013,010,NaN,NaN,4.0,NaN,2002.0,6.0
7,010013,040,NaN,NaN,4.0,NaN,2002.0,6.0
8,010038,010,NaN,NaN,5.0,NaN,2002.0,6.0
9,010038,040,NaN,NaN,6.0,NaN,2002.0,6.0
10,010050,010,NaN,NaN,5.0,NaN,2002.0,6.0
11,010059,020,NaN,NaN,5.0,NaN,2002.0,6.0
12,010059,030,NaN,NaN,6.0,NaN,2002.0,6.0
13,010075,020,NaN,NaN,7.0,NaN,2002.0,6.0
14,010075,030,NaN,NaN,7.0,NaN,2002.0,6.0
15,010083,010,NaN,3,4.0,NaN,2002.0,6.0
16,010083,020,NaN,NaN,4.0,NaN,2002.0,6.0
17,010097,040,NaN,NaN,4.0,NaN,2002.0,6.0
18,010099,010,NaN,NaN,1.0,NaN,2003.0,6.0
19,010106,010,NaN,NaN,8.0,NaN,2002.0,6.0
20,010109,030,NaN,NaN,1.0,NaN,2003.0,6.0
21,010124,010,NaN,NaN,4.0,NaN,2002.0,6.0
22,010147,010,NaN,NaN,5.0,NaN,2002.0,6.0
23,010196,010,NaN,NaN,4.0,NaN,2002.0,6.0
24,010206,010,NaN,NaN,4.0,NaN,2002.0,6.0
25,010210,010,9000,3,5.0,NaN,2002.0,6.0
26,010210,020,NaN,NaN,5.0,NaN,2002.0,6.0
27,010225,010,NaN,NaN,4.0,NaN,2002.0,6.0
28,010240,010,4000,7,10.0,NaN,2002.0,6.0
29,010281,010,NaN,NaN,5.0,NaN,2002.0,6.0
...,...,...,...,...,...,...,...,...
20882,920645,010,NaN,NaN,9.0,NaN,2016.0,13.0
20883,920653,010,NaN,2,8.0,NaN,2016.0,13.0
20884,920672,010,NaN,NaN,11.0,NaN,2016.0,13.0
20885,920672,020,NaN,NaN,3.0,NaN,2017.0,13.0
20886,920677,010,21177,NaN,8.0,NaN,2016.0,13.0
20887,920677,020,NaN,NaN,7.0,NaN,2016.0,13.0
20888,920690,010,NaN,NaN,10.0,5,2016.0,13.0
20889,920697,010,NaN,NaN,6.0,NaN,2016.0,13.0
20890,920735,010,1e+07,NaN,8.0,NaN,2017.0,13.0
20891,920735,020,30000,5,8.0,NaN,2017.0,13.0
20892,920736,010,NaN,NaN,6.0,NaN,2016.0,13.0
20893,920736,020,NaN,NaN,8.0,NaN,2016.0,13.0
20894,920753,010,NaN,NaN,1.0,NaN,2017.0,13.0
20895,920753,020,NaN,NaN,1.0,NaN,2017.0,13.0
20896,920760,010,NaN,7,8.0,NaN,2016.0,13.0
20897,920760,020,NaN,NaN,8.0,NaN,2016.0,13.0
20898,920772,010,NaN,NaN,6.0,8,2016.0,13.0
20899,923333,010,NaN,4,8.0,NaN,2017.0,13.0
20900,923486,010,NaN,NaN,11.0,NaN,2016.0,13.0
20901,923487,010,NaN,NaN,2.0,NaN,2017.0,13.0
20902,923489,010,NaN,NaN,11.0,NaN,2017.0,13.0
20903,923489,020,NaN,2,6.0,4,2016.0,13.0
20904,923497,010,NaN,NaN,2.0,NaN,2017.0,13.0
20905,923497,020,NaN,NaN,2.0,NaN,2017.0,13.0
20906,923498,010,NaN,NaN,11.0,1,2016.0,13.0
20907,923525,010,NaN,NaN,8.0,NaN,2016.0,13.0
20908,923525,020,NaN,5,1.0,NaN,2017.0,13.0
20909,952836,010,NaN,3,8.0,NaN,2016.0,13.0
20910,958361,010,NaN,NaN,9.0,NaN,2016.0,13.0
20911,959738,010,NaN,NaN,6.0,3,2016.0,13.0

In [11]:
output.groupby('wave').count()

,HHID,PN,rhosp_cost_oop,rjobwhym1,rmonth_survey,rrisk_financial,ryear_survey
wave,,,,,,,
6.0,18167,18167,2017,2434,18167,0,18167
7.0,20129,20129,2306,1663,20129,0,20129
8.0,18469,18469,2227,2026,18469,0,18469
9.0,17217,17217,2153,1731,17217,0,17217
11.0,20554,20554,2776,2191,20554,0,20554
12.0,18747,18747,2042,2061,18747,7350,18747
13.0,20912,20912,2317,2750,20912,6235,20912

In [12]:
year_frame.groupby('ryear_survey').count()
temp_df.groupby('ryear_survey').count()

year_frame.append(temp_df).groupby('wave').count()

,HHID,PN,rhosp_cost_oop,rjobwhym1,rmonth_survey,rrisk_financial,ryear_survey
wave,,,,,,,
12.0,18747,18747,2042,2061,18747,7350,18747
13.0,20912,20912,2317,2750,20912,6235,20912

In [ ]:
new_test = year_frame.merge(test, on = ['HHID', 'PN'], how = 'outer')
new_test.loc[pd.isna(new_test.PA500_x)]